#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 26 16:22:40 2023

@author: neihien
"""

import numpy as np
import pandas as pd
import cv2 as cv
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
import plotly.express as px

# Loading dataset
df = pd.read_csv('Data/data.csv')
pd.options.display.max_rows = 100
NB_SAMPLES = 20

# Error corecction
x = df['x']
df['x'] = df['angle']
df['angle'] = x

y = df['y']
df['y'] = df['dist']
df['dist'] = y